import os

WINDOW_SIZE = (1024, 600)
TARGET_FPS = 60
TILE_AMOUNTS = (16, 9)
ENEMY_SPAWN_RATE = (3, 5)
FOLDERPATH = os.path.split(os.path.realpath(__file__))[0]
EXECUTION_TIMER = 30
SPIKESTHRESHOLD = 80
WALLTHRESHOLD = 70
SPAWN_DIST_FROM_PLAYER = 10